### ISSUE TITLE
jQuery unneeded in bundle

### ISSUE THREAD

**Issue by Worthy7** [nhn/tui.date-picker#16]
Hi there, look at this:

![image](https://user-images.githubusercontent.com/4762399/42979009-f3cc85fc-8c0a-11e8-89b6-6cd404dbd659.png)

This shows that your date-picker (and time-picker) are pulling in TWO EXTRA versions of jquery that I do not need.

Can you please make them a peer-dependency so that we can manage it ourselves in the NPM bundle. This will make my angular app considerably lighter.

**Comment by lachlan-harris** [comment]
Hi there - what software are you using to view your project like this? It may come in handy for us

**Comment by Worthy7** [comment]
@lachlan-harris https://chrisbateman.github.io/webpack-visualizer/

**Comment by jung-han** [comment]
@Worthy7 Sorry for late. I'll check it out ASAP.

**Comment by J0sh0nat0r** [comment]
Looks like this is due to `time-picker` and `date-picker` depending on an outdated version of jQuery, thus causing npm to be unable dedupe it. It appears the solution would be to update `time-picker` and `date-picker` to the latest version of jQuery, provided that won't cause any issues.

**Comment by jung-han** [comment]
@J0sh0nat0r 
Thanks for issue. It could be a solution, We have planned to remove jQuery dependencies from the past. If we have a specific plan, I will let you know.
