### ISSUE TITLE
How to start the calendar with Monday and not Sunday?

### ISSUE THREAD

**Issue by awgul** [nhn/tui.date-picker#18]
Hey,

How to achieve this?
I've been looking in the API and I don't such option.

**Comment by jung-han** [comment]
@awgul Sorry for late. 
We don't have such options.
But It seems to be a necessary option. I'll review it ASAP

**Comment by TunedForLife** [comment]
Hello, will this feature be available anytime soon?

**Comment by dotaitch** [comment]
@TunedForLife 
We have a plan to implement this feature by September.

**Comment by akavato** [comment]
Hi! Any updates on this issue? Or maybe there is some workaround?

**Comment by kferenc** [comment]
Any updates on this issue?

**Comment by lja1018** [comment]
@akavato @kferenc 
Sorry for the late reply. We will update it within the next month. Thank you!

**Comment by dvsnic** [comment]
This function are working?

**Comment by lja1018** [comment]
@awgul @TunedForLife @akavato @kferenc 
The `weekStartDay` option was added in v4.2.0! Thank you.

**Comment by kferenc** [comment]
Thanks, but there is two problem:

- no dist folder in the new release
- weekStartDay option doesnt work with rangepicker

Please fix it!

**Comment by lja1018** [comment]
@kferenc 
Thank you for the information.
* The `dist` folder is located in the `production` branch.
* Try putting `weekStartDay` option in `startPicker` and `endPicker` for rangePicker. [link](https://nhn.github.io/tui.date-picker/latest/DateRangePicker)

**Comment by martinagrbic** [comment]
Hi guys I cant get weekStartDay working. I get following error: _Argument of type '{ language: string; input: { element: HTMLElement; format: string; }; date: Date; showAlways: false; weekStartDay: string; }' is not assignable to parameter of type 'DatePickerOptions'.
  Object literal may only specify known properties, and 'weekStartDay' does not exist in type 'DatePickerOptions'.ts(2345)_
this is the implementation :
 new DatePicker(container, {
      language: "customKey",
      input: {
        element: target,
        format: "yyyy-MM-dd",
      },
      date: new Date("06-06-2020"),
      showAlways: false,
      weekStartDay: "Mo",
    });
