### ISSUE TITLE
How to remove a date from an input after it has been selected in tui datepicker?

### ISSUE THREAD

**Issue by dvsnic** [nhn/tui.date-picker#69]
I am using Toast ui (tui) calendar datepicker. Tell me how to remove the selected date from input? When removed, the date is added to input again.
https://codepen.io/dvsnic/pen/YzpEyQj

**Comment by lja1018** [comment]
@dvsnic 
I don't understand the question. Are you saying that the input box values disappear when you turn on the calendar? Could you please write it down in detail again?

**Comment by dvsnic** [comment]
> @dvsnic
> I don't understand the question. Are you saying that the input box values disappear when you turn on the calendar? Could you please write it down in detail again?

Not. How can these values ​​be removed from input after selection?
http://joxi.ru/MAjL7ERU11w9zm

**Comment by lja1018** [comment]
@dvsnic 
If what I think is correct, I think you can select through the `select` event of `date-picker` and then remove the value of the input box.

**Comment by dvsnic** [comment]
> @dvsnic
> If what I think is correct, I think you can select through the `select` event of `date-picker` and then remove the value of the input box.

I guess I explained it wrong :)
How do I reset the date selection?
I tried like this: I set the cursor to input, pressed backspace, but the selected date is returned back. How do I reset it?
https://codepen.io/dvsnic/pen/YzpEyQj

**Comment by lja1018** [comment]
@dvsnic 
Oh, I think I understood. Try using the `setNull()` API. You can reset the selected date.

**Comment by dvsnic** [comment]
> @dvsnic
> Oh, I think I understood. Try using the `setNull()` API. You can reset the selected date.

Thanks, all worked well.
