### ISSUE TITLE
toast Grid와 겹침 현상

### ISSUE THREAD

**Issue by jsw-coder** [nhn/tui.date-picker#76]
안녕하세요

아래와 같이 Grid와 Date-Pick 사용시 겹침현상이 발생합니다. (크롬 브라우저 동일)

`
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'node_modules/tui-time-picker/dist/tui-time-picker.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/tui-date-picker/dist/tui-date-picker.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/tui-grid/dist/tui-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    

    <script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'node_modules/tui-code-snippet/dist/tui-code-snippet.js' %}"></script>
    <script src="{% static 'node_modules/tui-time-picker/dist/tui-time-picker.min.js' %}"></script>
    <script src="{% static 'node_modules/tui-date-picker/dist/tui-date-picker.min.js' %}"></script>
    <script src="{% static 'node_modules/tui-grid/dist/tui-grid.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>

</head>

<script>
function IsJsonString(str) {
    try {
    
        JSON.parse(str);
        alert("JSON OK");
    } catch (e) {
    alert("JSON NO");
        return false;
    }
    return true;
}

var grid;
    window.onload = function()
    {
       

   json_file ="{{param_values|escapejs}}";

    //IsJsonString(json_file);
    

    json_file = JSON.parse(json_file);

    //alert(typeof json == 'object');

    //alert("{{values}}");
    const data = json_file

        

      grid = new tui.Grid({
      el: document.getElementById('grid'),
      data, 
      //rowHeaders:["checkbox", "rowNum"],
     
      scrollX: false,
      scrollY: false,
      columns: [
        {
          header: 'EMPNO',
          name: 'EMPNO', 
          
          //editable:true
        },

        {
          header: 'FILE_NAME',
          name: 'FILE_NAME', 
          
          //editable:true
        },
        

       
      ],
    });

    $('button').click(function(){
             alert('test');
        $.ajax({
            url: "{% static 'js/index.js'%} "
                , method:"GET"
                , success: function(result) {
                    grid.resetData(eval(result))

                }

            });

    });//$('button').click(function(){

    tui.Grid.applyTheme("striped", {
         cell:{
             normal: {background:"#fff", 
             border:"#e0e0e0",
             showVerticalBorder:true, 
             showHorizontalBorder:true, 
         }, 
         

         header:{
             background:"#eaeaea", 
             border:"#e0e0e0",
             showVerticalBorder:true, 
             showHorizontalBorder:true, 
         },

         rowHeader:{
             background:"#eaeaea", 
             border:"#e0e0e0",
             showVerticalBorder:true, 
             showHorizontalBorder:true, 
         },
        }, 

    });//tui.Grid.applyTheme("normal", {

    //#####################datePick###########################################
     var today = new Date();
        var after_date = new Date();
        after_date.setDate(after_date.getDate() + 7)

    var picker = tui.DatePicker.createRangePicker({
        startpicker: {
            date: today,
            input: '#startpicker-input',
            container: '#startpicker-container'
        },
        endpicker: {
            date: after_date,
            input: '#endpicker-input',
            container: '#endpicker-container'
        },
        selectableRanges: [
            [today, new Date(today.getFullYear() + 1, today.getMonth(), today.getDate())]
        ]
    });
    //#####################datePick###########################################

    };//window.onload

   
     

</script>

<body>
    
    

    

    <div id="wrap">

        
        <div>

        <form action="#" method="post">
            {% csrf_token %}
            <input type="text" name="rownum" size="1"/>            
            <input type="submit" class="btn btn-primary btn-sm" value="mybtn" name="mybtn" >

              <div class="tui-datepicker-input tui-datetime-input tui-has-focus">
                <input id="startpicker-input" type="text" aria-label="Date">
                <span class="tui-ico-date"></span>
                <div id="startpicker-container" style="margin-left: -1px;"></div>
            </div>
            <span>to</span>
            <div class="tui-datepicker-input tui-datetime-input tui-has-focus">
                <input id="endpicker-input" type="text" aria-label="Date">
                <span class="tui-ico-date"></span>
                <div id="endpicker-container" style="margin-left: -1px;"></div>
            </div>

          

        </form>

        
            {#<button type="button" class="btn btn-primary btn-sm">조회</button>#}
        </div>

        <div id="grid"></div>

        
    </div>
    
</body>

</html>
`

![image](https://user-images.githubusercontent.com/81946046/117773846-c6ba1880-b273-11eb-8d7e-70636a212e22.png)

**Comment by lja1018** [comment]
@jsw-coder 
질문해주셔서 감사합니다. 올려주신 코드와 html 파일로는 정확한 파악이 어렵습니다. [code sandbox](https://codesandbox.io/) 같은 툴을 이용해서 예제를 올려주시면 감사하겠습니다.
또 이슈는 영어로 올리는게 원칙이라 다음부터는 영어로 올려주시면 감사하겠습니다.
