### ISSUE TITLE
Month and year selectors are not opening

### ISSUE THREAD

**Issue by martinagrbic** [nhn/tui.date-picker#81]
## Describe the bug
Open datepicker click on selected month and year, select for month and year are not opened
## To Reproduce
1. Open datepicker 
2. click on selected month and year
3. datepicker is closed
## Expected behavior
selection for the month is opened

## Desktop (please complete the following information):
 - OS: Linux
 - Browser chrome

**Comment by martinagrbic** [comment]
My further investigation showed that this issue happens because of the shadow dom. I am creating web components based on lit. When shadow dom is enabled dates are not selectable and month and year selects can't be opened.

**Comment by jajugoguma** [comment]
@martinagrbic 
We currently do not support shadow dom.
There are many things to consider to support it, so we will work with caution when applying it later.

Thanks for your interest.
