### ISSUE TITLE
Today Button, Year SelectBox, Month SelectBox Add Request

### ISSUE THREAD

**Issue by DBSSU77** [nhn/tui.date-picker#87]
**Version**
3.3.4

**Development Environment**
JavaScript, JQuery

**Request**
1. Please add today's date selection button function.
2. Please add a year selection SelectBox function.
3. Please add a monthly selection SelectBox function.

**Comment by jajugoguma** [comment]
@DBSSU77 
We'll consider adding today's date selection button.
We already support the function that year and month selection on SelectBox like the below video.

![](https://user-images.githubusercontent.com/41339744/126747520-1d912287-f291-491c-8826-174a6284d8ea.gif)

If I misunderstand what you said, tell me more information about this.

**Comment by DBSSU77** [comment]
This image is an example.
We customer wants to select using the SelectBox.
![NVtQY](https://user-images.githubusercontent.com/87845639/126750090-27d50771-2cfb-4181-b0fc-fef190f19236.jpg)

**Comment by jajugoguma** [comment]
@DBSSU77 
Rather than adding the function inside the date picker, you should add it using the external select box and the 'setDate' and 'open' APIs.
